version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.8.16-management-alpine
    ports:
    - 5672:5672
    - 15672:15672
#    volumes:
#    - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq.conf:rw
#    - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:rw
    environment:
      RABBITMQ_DEFAULT_USER: "wabbit"
      RABBITMQ_DEFAULT_PASS: "password"
